os: linux
language: node_js
node_js:
  - "14"
dist: trusty

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href http://teensy-client.s3-website.ap-south-1.amazonaws.com

deploy:
  provider: s3
  bucket: "teensy-client"
  region: "ap-south-1"
  skip_cleanup: true
  local_dir: dist/teensy-client
  edge: true
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
